# Generated by Django 4.0.6 on 2022-08-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
