# Generated by Django 4.0.6 on 2022-09-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='out_for_delivery',
            field=models.DateTimeField(blank=True, default=True, null=True),
        ),
    ]
