# Generated by Django 4.0.6 on 2022-09-29 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_coupan_maximum_usage_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_offer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.product'),
        ),
    ]
