# Generated by Django 4.0.6 on 2022-10-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_salesreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
